import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { CycleCell } from '@/types'

const DAY_LABELS = ['一', '二', '三', '四', '五', '六', '日']

export function exportScheduleToPDF(
  cycleName: string,
  personName: string,
  totalWeeks: number,
  cells: CycleCell[]
) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  })

  // Build cell map
  const cellMap = new Map<string, string[]>()
  for (const cell of cells) {
    const key = `${cell.week_number}-${cell.day_of_week}`
    if (!cellMap.has(key)) cellMap.set(key, [])
    if (cell.display_value) cellMap.get(key)!.push(cell.display_value)
  }

  // Title
  doc.setFontSize(16)
  doc.text(`${personName} - ${cycleName || 'Cycle'}`, 14, 15)

  // Table data
  const headers = ['Week', ...DAY_LABELS]
  const body: string[][] = []

  for (let week = 1; week <= totalWeeks; week++) {
    const row = [`Week ${week}`]
    for (let day = 1; day <= 7; day++) {
      const key = `${week}-${day}`
      const entries = cellMap.get(key) || []
      row.push(entries.join('\n'))
    }
    body.push(row)
  }

  autoTable(doc, {
    startY: 22,
    head: [headers],
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [40, 40, 40],
      textColor: [255, 255, 255],
      fontSize: 9,
      halign: 'center',
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
      valign: 'top',
      lineWidth: 0.1,
    },
    columnStyles: {
      0: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 35 },
      5: { cellWidth: 35 },
      6: { cellWidth: 35 },
      7: { cellWidth: 35 },
    },
    styles: {
      overflow: 'linebreak',
      cellWidth: 'wrap',
    },
    margin: { left: 10, right: 10 },
    didDrawPage: (data) => {
      // Footer
      doc.setFontSize(7)
      doc.setTextColor(150)
      doc.text(
        `Generated by Cycle Planner - ${new Date().toLocaleDateString('zh-TW')}`,
        14,
        doc.internal.pageSize.height - 8
      )
    },
  })

  doc.save(`${personName}_${cycleName || 'cycle'}.pdf`)
}
