import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { CycleCell, DrugInventoryDelta } from '@/types'

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

export function exportScheduleToPDF(
  cycleName: string,
  personName: string,
  totalWeeks: number,
  cells: CycleCell[],
  deltas?: DrugInventoryDelta[]
) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  })

  // Build cell map
  const cellMap = new Map<string, string[]>()
  for (const cell of cells) {
    const key = `${cell.week_number}-${cell.day_of_week}`
    if (!cellMap.has(key)) cellMap.set(key, [])
    if (cell.display_value) cellMap.get(key)!.push(cell.display_value)
  }

  // Title
  doc.setFontSize(16)
  doc.text(`${personName} - ${cycleName || 'Cycle'}`, 14, 15)

  // Schedule table
  const headers = ['Week', ...DAY_LABELS]
  const body: string[][] = []

  for (let week = 1; week <= totalWeeks; week++) {
    const row = [`Week ${week}`]
    for (let day = 1; day <= 7; day++) {
      const entries = cellMap.get(`${week}-${day}`) || []
      row.push(entries.join('\n'))
    }
    body.push(row)
  }

  autoTable(doc, {
    startY: 22,
    head: [headers],
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [40, 40, 40],
      textColor: [255, 255, 255],
      fontSize: 9,
      halign: 'center',
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
      valign: 'top',
      lineWidth: 0.1,
    },
    columnStyles: {
      0: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 35 },
      5: { cellWidth: 35 },
      6: { cellWidth: 35 },
      7: { cellWidth: 35 },
    },
    styles: {
      overflow: 'linebreak',
      cellWidth: 'wrap',
    },
    margin: { left: 10, right: 10 },
    didDrawPage: () => {
      doc.setFontSize(7)
      doc.setTextColor(150)
      doc.text(
        `Generated by Cycle Planner - ${new Date().toLocaleDateString('zh-TW')}`,
        14,
        doc.internal.pageSize.height - 8
      )
    },
  })

  // Drug stats table
  if (deltas && deltas.length > 0) {
    const finalY = (doc as any).lastAutoTable?.finalY || 22
    const startY = finalY + 10

    doc.setFontSize(11)
    doc.setTextColor(0)
    doc.text('Drug Stats', 14, startY)

    const statsHeaders = ['Drug', 'Needed', 'Qty']
    const statsBody = deltas.map((d) => {
      const isOral = d.category === 'Oral' || d.category === 'PCT'
      return [
        d.drug_name,
        isOral ? `${d.needed_ml} tabs` : `${d.needed_ml} ml`,
        isOral ? `${d.needed_vials} box` : `${d.needed_vials} vial`,
      ]
    })

    autoTable(doc, {
      startY: startY + 3,
      head: [statsHeaders],
      body: statsBody,
      theme: 'grid',
      headStyles: {
        fillColor: [40, 40, 40],
        textColor: [255, 255, 255],
        fontSize: 8,
        halign: 'center',
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 2,
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 30, halign: 'right' },
        2: { cellWidth: 30, halign: 'right' },
      },
      margin: { left: 10, right: 10 },
      tableWidth: 100,
    })
  }

  doc.save(`${personName}_${cycleName || 'cycle'}.pdf`)
}
